version: 2.1
# install all requirements dependancies here we need (node, eb, aws-cli)
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
# jobs founded in pipeline
jobs:
  # build steps to both front and backend
  build:
    docker:
      # create docker image
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'         
      - checkout
      # start run code from main packige.jason
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      # install API Dependencies          
      - run:
          name: Install API Dependencies
          command: |
           npm run api:install
      # build frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # build backend      
      - run:
          name: API Build
          command: |
            npm run api:build
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '14.15' 
      - eb/setup
      - aws-cli/setup
      - checkout

      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
      # set project environment
      - run:
          name: init eb and aws
          command: >
            cd udagram/udagram-api &&
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME
            POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            POSTGRES_DB=$POSTGRES_DB
            POSTGRES_HOST=$POSTGRES_HOST
            JWT_SECRET=$JWT_SECRET
      # deploy app to aws
      - run:
          name: Deploy App
          command: |
            npm run deploy
workflows:
  udagram:
    jobs:
      - build
      - deploy:
          requires:
            - build
